// <auto-generated />
using System;
using KYCVerificationAPI.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace KYCVerificationAPI.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20250507051857_UpdateVerification")]
    partial class UpdateVerification
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.4")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("KYCVerificationAPI.Data.Entities.Verification", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("CardNumber")
                        .IsRequired()
                        .HasColumnType("varchar(10)");

                    b.Property<bool?>("CardNumberAsPerIdMatches")
                        .HasColumnType("boolean");

                    b.Property<string>("CorrelationId")
                        .IsRequired()
                        .HasColumnType("varchar(50)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("CreatedBy")
                        .IsRequired()
                        .HasColumnType("varchar(25)");

                    b.Property<DateOnly>("DateOfBirth")
                        .HasColumnType("date");

                    b.Property<bool?>("DateOfBirthMatches")
                        .HasColumnType("boolean");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasColumnType("varchar(25)");

                    b.Property<string>("GivenName")
                        .IsRequired()
                        .HasColumnType("varchar(25)");

                    b.Property<string>("KycMessage")
                        .HasColumnType("varchar(50)");

                    b.Property<int>("KycStatus")
                        .HasColumnType("integer");

                    b.Property<DateTime?>("LastUpdated")
                        .HasColumnType("timestamp with time zone");

                    b.Property<bool?>("NameAsPerIdMatches")
                        .HasColumnType("boolean");

                    b.Property<string>("Nin")
                        .IsRequired()
                        .HasColumnType("varchar(14)");

                    b.Property<bool?>("NinAsPerIdMatches")
                        .HasColumnType("boolean");

                    b.Property<int?>("Retries")
                        .HasColumnType("integer");

                    b.Property<int>("Status")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("CardNumber");

                    b.HasIndex("CreatedAt");

                    b.HasIndex("CreatedBy");

                    b.HasIndex("FirstName");

                    b.HasIndex("GivenName");

                    b.HasIndex("Nin");

                    b.ToTable("Verifications");
                });
#pragma warning restore 612, 618
        }
    }
}
